theme = "hugo-lithium"
baseURL = "https://www.maxmantei.com"
languageCode = "en-us"
title = "Max's Blog"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.

googleAnalytics = "UA-164799772-1"
disqusShortname = "maxmantei"

enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true
enableMissingTranslationPlaceholders = true
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[author]
  name = "Max Mantei"
  
[taxonomies]
  tag      = "tags"
  category = "categories"


[permalinks]
    post = "/:year/:month/:day/:slug/"
    
[[menu.main]]
    name = "Blog"
    url = "/post/"    
    
[[menu.main]]
    name = "About"
    url = "/about/"

[[menu.main]]
    #name = "GitHub"
    #url = "https://github.com/rstudio/blogdown"
[[menu.main]]
    #name = "Twitter"
    #url = "https://twitter.com/rstudio"

[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "10.4.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml", "python", "stan", "bash", "toml", "shell", "julia"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.9"

    # path to the favicon, under "static"
    #favicon = "favicon.ico"

    [params.logo]
    #url = "logo.png"
    #width = 50
    #height = 50
    #alt = "Logo"

[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.instagram]
    disable = true
    simple = false
  [privacy.twitter]
    disable = true
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = true
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = true
